parameters:
  "service-dir":
    default: "schema"
emit:
  - "@typespec/openapi3"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/{service-dir}"
    openapi-versions:
      - 3.1.0
